INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:07:55.707278 : Excel file '1401-03-01.xlsx' saved to 'datalake\1401-03-01.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:07:57.138275 : Excel file '1401-03-02.xlsx' saved to 'datalake\1401-03-02.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:07:58.648634 : Excel file '1401-03-03.xlsx' saved to 'datalake\1401-03-03.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:08:00.24125 : Excel file '1401-03-04.xlsx' saved to 'datalake\1401-03-04.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:08:00.397137 : Excel file '1401-03-07.xlsx' saved to 'datalake\1401-03-07.xlsx' successfully.
ERROR:root:extract_transactions_xlsx_files.py 1402-10-24 22:08:21.446750 : HTTPConnectionPool(host='members.tsetmc.com', port=80): Max retries exceeded with url: /tsev2/excel/MarketWatchPlus.aspx?d=1401-03-08 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000013309CE8150>, 'Connection to members.tsetmc.com timed out. (connect timeout=None)'))
INFO:root:convert_xlsx_files_to_csv_files.py 2024-01-14 22:08:21.884583 : 1401-03-01.xlsx was successfully converted to csv and saved to .\stage
INFO:root:convert_xlsx_files_to_csv_files.py 2024-01-14 22:08:22.078106 : 1401-03-02.xlsx was successfully converted to csv and saved to .\stage
INFO:root:convert_xlsx_files_to_csv_files.py 2024-01-14 22:08:22.285346 : 1401-03-03.xlsx was successfully converted to csv and saved to .\stage
INFO:root:convert_xlsx_files_to_csv_files.py 2024-01-14 22:08:22.497777 : 1401-03-04.xlsx was successfully converted to csv and saved to .\stage
INFO:root:convert_xlsx_files_to_csv_files.py 2024-01-14 22:08:22.682285 : 1401-03-07.xlsx was successfully converted to csv and saved to .\stage
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:08:54.122869 : Excel file '1401-03-01.xlsx' saved to 'datalake\1401-03-01.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:17:28.125994 : Excel file '1401-03-01.xlsx' saved to 'datalake\1401-03-01.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:17:28.684909 : Excel file '1401-03-02.xlsx' saved to 'datalake\1401-03-02.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:17:29.290388 : Excel file '1401-03-03.xlsx' saved to 'datalake\1401-03-03.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:17:29.822253 : Excel file '1401-03-04.xlsx' saved to 'datalake\1401-03-04.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:17:30.355028 : Excel file '1401-03-07.xlsx' saved to 'datalake\1401-03-07.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:17:30.923330 : Excel file '1401-03-08.xlsx' saved to 'datalake\1401-03-08.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:17:31.554279 : Excel file '1401-03-09.xlsx' saved to 'datalake\1401-03-09.xlsx' successfully.
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:17:32.127333 : Excel file '1401-03-10.xlsx' saved to 'datalake\1401-03-10.xlsx' successfully.
ERROR:root:convert_xlsx_files_to_csv_files.py 2024-01-14 22:17:32.588574 : [WinError 161] The specified path is invalid: '///\\'
ERROR:root:extract_transactions_xlsx_files.py 1402-10-24 22:22:25.560737 : HTTPConnectionPool(host='members.tsetmc.com', port=80): Max retries exceeded with url: /tsev2/excel/MarketWatchPlus.aspx?d=1401-03-01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000180B1A10ED0>: Failed to establish a new connection: [WinError 10053] An established connection was aborted by the software in your host machine'))
ERROR:root:convert_xlsx_files_to_csv_files.py 2024-01-14 22:22:26.620905 : [WinError 161] The specified path is invalid: '///\\'
ERROR:root:extract_transactions_xlsx_files.py 1402-10-24 22:22:52.824747 : HTTPSConnectionPool(host='members.tsetmc.com', port=443): Max retries exceeded with url: /tsev2/excel/MarketWatchPlus.aspx?d=1401-03-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000015D85781410>, 'Connection to members.tsetmc.com timed out. (connect timeout=None)'))
ERROR:root:convert_xlsx_files_to_csv_files.py 2024-01-14 22:22:53.275126 : [WinError 161] The specified path is invalid: '///\\'
ERROR:root:extract_transactions_xlsx_files.py 1402-10-24 22:24:04.880704 : HTTPSConnectionPool(host='members.tsetmc.com', port=443): Max retries exceeded with url: /tsev2/excel/MarketWatchPlus.aspx?d=1401-03-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000026F0787D150>, 'Connection to members.tsetmc.com timed out. (connect timeout=None)'))
ERROR:root:convert_xlsx_files_to_csv_files.py 2024-01-14 22:24:05.372153 : [WinError 161] The specified path is invalid: '///\\'
INFO:root:extract_transactions_xlsx_files.py 1402-10-24 22:24:36.935304 : Excel file '1401-03-01.xlsx' saved to 'datalake\1401-03-01.xlsx' successfully.
ERROR:root:extract_transactions_xlsx_files.py 1402-10-24 22:24:57.983052 : HTTPConnectionPool(host='members.tsetmc.com', port=80): Max retries exceeded with url: /tsev2/excel/MarketWatchPlus.aspx?d=1401-03-02 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000024CFFD4FA90>, 'Connection to members.tsetmc.com timed out. (connect timeout=None)'))
ERROR:root:convert_xlsx_files_to_csv_files.py 2024-01-14 22:24:58.478338 : [WinError 161] The specified path is invalid: '///\\'
